name: Test Report
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Display test report
        uses: dorny/test-reporter@v1.6.0
        with:
          artifact: test-results
          name: JUnit Tests
          path: '**/*.xml'
          reporter: java-junit
